-- 시퀀트 테스트용 테이블 생성
CREATE TABLE test (
    NO NUMBER NOT NULL PRIMARY KEY  -- 기본 키로 사용할 번호
    
);


-- 시퀀스 생성
CREATE SEQUENCE test_seq
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 100000
NOCYCLE
CACHE 2;

COMMIT;

DROP SEQUENCE test_seq;

ROLLBACK;


-- NEXTVAL 테스트
SELECT test_seq.NEXTVAL
FROM DUAL;


-- CURRVAL 테스트
SELECT test_seq.CURRVAL
FROM DUAL;


-- INSERT 문으로 시퀀스 값 입력하기
INSERT INTO TEST(NO)
VALUES(test_seq.NEXTVAL);

SELECT * FROM test;



INSERT INTO TEST
VALUES((SELECT NVL(MAX(NO), 0) +1 FROM TEST));


DROP TABLE test purge;
DROP SEQUENCE test_seq;



CREATE TABLE test (
    no NUMBER NOT NULL PRIMARY KEY,  -- 기본 키로 사용할 번호
    name NVARCHAR2(5) NOT NULL,
    email VARCHAR2(50) NOT NULL,
    regdate DATE DEFAULT SYSDATE
);

CREATE SEQUENCE test_seq 
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    MINVALUE 1
    NOCYCLE
    CACHE 2;


INSERT INTO test(no, name, email)
VALUES(test_seq.NEXTVAL, '한진형', 'dwune@naver.com');

INSERT INTO test(no, name, email)
VALUES(test_seq.NEXTVAL, '강기연', 'kky@naver.com');

INSERT INTO test(no, name, email)
VALUES(test_seq.NEXTVAL, '임태형', 'limbak@naver.com');


SELECT * FROM test;


-- 시퀀스를 내부에 포함해서 기본값으로
CREATE TABLE test (
    no NUMBER DEFAULT test_seq.NEXTVAL NOT NULL PRIMARY KEY,  -- 기본 키로 사용할 번호
    name NVARCHAR2(5) NOT NULL,
    email VARCHAR2(50) NOT NULL,
    regdate DATE DEFAULT SYSDATE
);


INSERT INTO test(name, email)
VALUES('한진형', 'dwune@naver.com');

INSERT INTO test(name, email)
VALUES('강기연', 'kky@naver.com');

INSERT INTO test(name, email)
VALUES('임태형', 'limbak@naver.com');



-- 가상 컬럼을 포함한 테이블 PRODUCT_ORDER 생성
CREATE TABLE product_order (
    price       NUMBER,
    quantity    NUMBER,
    total_price NUMBER GENERATED ALWAYS AS (price * quantity) VIRTUAL
);

INSERT INTO product_order(price, quantity)
VALUES(10000, 3);

INSERT INTO product_order(price, quantity)
VALUES(30000, 2);

SELECT * FROM product_order;



-- IDENTITY 컬럼을 사용한 학생 테이블 생성
CREATE TABLE student (
    student_no NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_name NVARCHAR2(5) NOT NULL
);

INSERT INTO student(student_name) VALUES ('홍길동');
INSERT INTO student(student_name) VALUES ('김철수');

SELECT * FROM student;



-- [예제]
--GRADE 테이블은 국어, 영어, 수학 점수를 저장하는 테이블이다.
--성적 번호는 자동으로 생성되며, 총점과 평균은 가상 컬럼을 이용해 자동으로 계산된다.
--또한 각 과목 점수는 0점 이상 100점 이하만 입력할 수 있도록 CHECK 제약 조건을 설정하였다.
CREATE TABLE grade (
    no          NUMBER      GENERATED BY DEFAULT AS IDENTITY,
    kor_score   NUMBER(3)   NOT NULL,
    eng_score   NUMBER(3)   NOT NULL,
    math_score  NUMBER(3)   NOT NULL,
    total_score NUMBER(3)   GENERATED ALWAYS AS(kor_score + eng_score + math_score) VIRTUAL,
    avg_score   NUMBER(4,1) GENERATED ALWAYS AS(TRUNC((kor_score + eng_score + math_score)/3,1)) VIRTUAL,
    -- trunc 안에 AVG 사용 불가, total_score의 경우 가상 컬럼이어서 사용 불가.
    CONSTRAINT GRADE_NO_PK  PRIMARY KEY(no),
    CONSTRAINT GRADE_KOR_CK CHECK(kor_score BETWEEN 0 AND 100),
    CONSTRAINT GRADE_ENG_CK CHECK(eng_score BETWEEN 0 AND 100),
    CONSTRAINT GRADE_MATH_CK CHECK(math_score BETWEEN 0 AND 100)
);

--TRUNC(값, n) : 소수점 n번째 자리까지만 남기고 나머지 버림

INSERT INTO grade(kor_score, eng_score, math_score)
VALUES(90 ,90 ,90);

INSERT INTO grade(kor_score, eng_score, math_score)
VALUES(90 ,90 ,70);

INSERT INTO grade(kor_score, eng_score, math_score)
VALUES(0, 90 ,70);


SELECT * FROM grade;


