-- 1. 학과 테이블 생성.
-- 테이블명 : subject
DROP TABLE subject purge;

CREATE TABLE subject (
    no      NUMBER          GENERATED BY DEFAULT AS IDENTITY NOT NULL,  -- 일련번호
    s_num   VARCHAR2(2)     NOT NULL,                                   -- 학과번호
    s_name  NVARCHAR2(10)   NOT NULL,                                   -- 학과명
    CONSTRAINT SUBJECT_NO_PK PRIMARY KEY(no),   -- NO를 PK로 설정
    CONSTRAINT SUBJECT_S_NUM_UK UNIQUE(s_num)   -- S_NUM을 UK로 설정
);

INSERT INTO subject(s_num, s_name)
VALUES('01', '컴퓨터학과');

INSERT INTO subject(s_num, s_name)
VALUES('02', '교육학과');

INSERT INTO subject(s_num, s_name)
VALUES('03', '신문방송학과');

INSERT INTO subject(s_num, s_name)
VALUES('04', '인터넷비즈니스과');

INSERT INTO subject(s_num, s_name)
VALUES('05', '기술경영과');


SELECT * FROM subject;


-- 2. 학생 테이블 생성
DROP TABLE student purge;

CREATE TABLE student (
    no          NUMBER          GENERATED BY DEFAULT AS IDENTITY NOT NULL, -- 일련번호
    sd_num      NVARCHAR2(8)    NOT NULL,                                  -- 학번
    sd_name     NVARCHAR2(10)   NOT NULL,                                  -- 이름
    sd_id       NVARCHAR2(10)   NOT NULL,                                  -- 아이디
    sd_passwd   NVARCHAR2(10)   NOT NULL,                                  -- 비밀번호
    s_num       VARCHAR2(2)     NOT NULL,                                  -- 학과번호
    sd_birth    DATE            NOT NULL,                                  -- 생년월일
    sd_phone    NVARCHAR2(13)   NOT NULL,                                  -- 핸드폰번호
    sd_address  NVARCHAR2(50)   NOT NULL,                                  -- 주소
    sd_email    NVARCHAR2(30)   NOT NULL,                                  -- 이메일
    sd_date     DATE            DEFAULT SYSDATE NOT NULL,                  -- 등록일자
    CONSTRAINT STUDENT_NO_PK PRIMARY KEY(no),    -- NO를 PK로 설정
    CONSTRAINT STUDENT_SD_NUM_UK UNIQUE(sd_num),    -- SD_NUM을 UK로 설정
    CONSTRAINT STUDENT_ID_UK UNIQUE(sd_id),      -- SD_ID를 UK로 설정
    CONSTRAINT STUDENT_S_NUM_FK FOREIGN KEY(s_num) REFERENCES subject(s_num)  -- S_NUM을 FK로 설정
);


INSERT INTO student(sd_num, sd_name, sd_id, sd_passwd, s_num, sd_birth, sd_phone, sd_address, sd_email)
VALUES('06010001', '김정수', 'javajsp', '111234', '01', '20000101', '010-1234-2356', '(03727) 서울특별시 서대문구 성산로 450-2', 'javajsp@naver.com');

INSERT INTO student(sd_num, sd_name, sd_id, sd_passwd, s_num, sd_birth, sd_phone, sd_address, sd_email)
VALUES('95010002', '김수현', 'jdbcmania', '111234', '02', '20000101', '010-2222-3333', '(06774) 서울특별시 서초구 강남대로 27', 'jdbcmaniap@naver.com');

INSERT INTO student(sd_num, sd_name, sd_id, sd_passwd, s_num, sd_birth, sd_phone, sd_address, sd_email)
VALUES('98040001', '공지영', 'gonji', '111234', '03', '20000101', '010-1470-2580', '(48000) 부산광역시 해운대구 반송로 816', 'gonji@naver.com');

INSERT INTO student(sd_num, sd_name, sd_id, sd_passwd, s_num, sd_birth, sd_phone, sd_address, sd_email)
VALUES('02050001', '조수영', 'water', '111234', '04', '20000101', '010-9874-9632', '(34626) 대전광역시 동구 중앙로 215', 'water@naver.com');

INSERT INTO student(sd_num, sd_name, sd_id, sd_passwd, s_num, sd_birth, sd_phone, sd_address, sd_email)
VALUES('94040002', '최경란', 'novel', '111234', '05', '20000101', '010-7777-8888', '(16210) 경기도 수원시 장안구 서부로 2287-55', 'novel@naver.com');

INSERT INTO student(sd_num, sd_name, sd_id, sd_passwd, s_num, sd_birth, sd_phone, sd_address, sd_email)
VALUES('08020001', '안익태', 'korea', '111234', '04', '20000101', '010-2468-1357', '(00000) 대한민국 어딘가', 'korea@naver.com');


SELECT * FROM student;


-- 3. 과목테이블을 생성한다.
DROP TABLE course purge;

CREATE TABLE course (
    no          NUMBER          GENERATED BY DEFAULT AS IDENTITY NOT NULL, -- 일련번호
    c_num       VARCHAR2(7)     NOT NULL,                                  -- 과목번호
    c_name      NVARCHAR2(20)   NOT NULL,                                  -- 과목명
    c_credit    NUMBER          NOT NULL,                                  -- 학점
    c_section   NVARCHAR2(2)    NOT NULL,                                  -- 과목구분
    CONSTRAINT COURSE_NO_PK PRIMARY KEY(no),    -- NO를 PK로 설정
    CONSTRAINT COURSE_C_NUM_UK UNIQUE(c_num),    -- C_NUM을 UK로 설정
    CONSTRAINT COURSE_C_CREDIT_CK CHECK(c_credit BETWEEN 2 AND 4),
    CONSTRAINT COURSE_C_SECTION_CK CHECK(c_section IN ('전공', '교양', '일반'))
);

INSERT INTO course(c_num, c_name, c_credit, c_section)
VALUES('UA04001', '대학영어', 2, '교양');

INSERT INTO course(c_num, c_name, c_credit, c_section)
VALUES('UA05001', '소프트웨어와 창의적 사고', 4, '교양');

INSERT INTO course(c_num, c_name, c_credit, c_section)
VALUES('UBB0001', '독서와 토론', 3, '교양');

INSERT INTO course(c_num, c_name, c_credit, c_section)
VALUES('UGG0010', '한국의 이해' , 3, '일반');

INSERT INTO course(c_num, c_name, c_credit, c_section)
VALUES('UGG0031', '내아이디어로 창업하기', 4, '일반');

INSERT INTO course(c_num, c_name, c_credit, c_section)
VALUES('UCR0001', '데이터베이스 설계와 구축', 4, '전공');

INSERT INTO course(c_num, c_name, c_credit, c_section)
VALUES('UCR0002', '데이터 분석', 4, '전공');

SELECT * FROM course;


-- 4. 수강테이블을 생성한다.
DROP TABLE enrollment purge;
CREATE TABLE enrollment (
    no          NUMBER          GENERATED BY DEFAULT AS IDENTITY NOT NULL, -- 일련번호
    e_year      NUMBER          NOT NULL,                                  -- 수강년도
    e_semester  NVARCHAR2(4)    NOT NULL,                                  -- 수강학기
    sd_num      NVARCHAR2(8)    NOT NULL,                                  -- 학번
    c_num       VARCHAR2(7)     NOT NULL,                                  -- 과목번호
    e_grade     NUMBER(2,1)     NOT NULL,                                  -- 성적
    e_date      DATE            DEFAULT SYSDATE NOT NULL,                  -- 등록일자
    CONSTRAINT ENROLLMENT_NO_PK PRIMARY KEY(no),    -- NO를 PK로 설정
    CONSTRAINT ENROLLMENT_E_SEMESTER_CK CHECK(e_semester IN ('1학기', '2학기', '여름학기', '겨울학기')),
    CONSTRAINT ENROLLMENT_SD_NUM_FK FOREIGN KEY(sd_num) REFERENCES student(sd_num),  -- SD_NUM을 FK로 설정
    CONSTRAINT ENROLLMENT_C_NUM_FK FOREIGN KEY(c_num) REFERENCES course(c_num),  -- C_NUM을 FK로 설정
    CONSTRAINT ENROLLMENT_E_GRADE_CK CHECK(e_grade BETWEEN 0 AND 4.5)
);

INSERT INTO enrollment(e_year, e_semester, sd_num, c_num, e_grade)
VALUES(2004, '1학기', '06010001', 'UA05001', 4.0);

INSERT INTO enrollment(e_year, e_semester, sd_num, c_num, e_grade)
VALUES(2004, '1학기', '98040001', 'UBB0001', 3.8);

INSERT INTO enrollment(e_year, e_semester, sd_num, c_num, e_grade)
VALUES(2004, '1학기', '06010001', 'UCR0001', 4.3);

INSERT INTO enrollment(e_year, e_semester, sd_num, c_num, e_grade)
VALUES(2004, '1학기', '08020001' , 'UGG0031', 3.6);


SELECT * FROM enrollment;




-- 자방 예제에 사용하기 위해 수정


-- 1. 과목 테이블
CREATE TABLE subject (
    no      NUMBER          GENERATED BY DEFAULT AS IDENTITY,           -- 일련번호
    s_num   CHAR(2)         GENERATED ALWAYS AS (                       -- 학과번호
                            CAST(LPAD(TO_CHAR(NO), 2, '0') AS CHAR(2))
                            ) VIRTUAL,                                  
    s_name  VARCHAR2(80)   NOT NULL,                                   -- 학과명
    CONSTRAINT SUBJECT_NO_PK PRIMARY KEY(no),   -- NO를 PK로 설정
    CONSTRAINT SUBJECT_S_NUM_UK UNIQUE(s_num),   -- S_NUM을 UK로 설정
    CONSTRAINT subject_no_ck CHECK(no BETWEEN 1 AND 99)
);

INSERT INTO subject(s_name)
VALUES('컴퓨터학과');

INSERT INTO subject(s_name)
VALUES('교육학과');

INSERT INTO subject(s_name)
VALUES('신문방송학과');

INSERT INTO subject(s_name)
VALUES('인터넷비즈니스과');

INSERT INTO subject(s_name)
VALUES('기술경영과');

COMMIT;

SELECT no, s_num, s_name FROM subject
ORDER BY no;



-- 2. 학생 테이블
DROP TABLE student purge;
CREATE TABLE student (
    no          NUMBER          GENERATED BY DEFAULT AS IDENTITY NOT NULL, -- 일련번호
    sd_num      CHAR(8)         NOT NULL,                                  -- 학번
    sd_name     NVARCHAR2(10)   NOT NULL,                                  -- 이름
    sd_id       VARCHAR2(15)   NOT NULL,                                  -- 아이디
    sd_passwd   VARCHAR2(15)   NOT NULL,                                  -- 비밀번호
    s_num       CHAR(2)         NOT NULL,                                  -- 학과번호
    sd_birth    DATE            NOT NULL,                                  -- 생년월일
    sd_phone    VARCHAR2(15)   NOT NULL,                                  -- 핸드폰번호
    sd_address  NVARCHAR2(100)  NOT NULL,                                  -- 주소
    sd_email    VARCHAR2(100)  NOT NULL,                                  -- 이메일
    sd_date     DATE            DEFAULT SYSDATE NOT NULL,                  -- 등록일자
    CONSTRAINT STUDENT_NO_PK PRIMARY KEY(no),    -- NO를 PK로 설정
    CONSTRAINT STUDENT_SD_NUM_UK UNIQUE(sd_num),    -- SD_NUM을 UK로 설정
    CONSTRAINT STUDENT_ID_UK UNIQUE(sd_id),      -- SD_ID를 UK로 설정
    CONSTRAINT STUDENT_S_NUM_FK FOREIGN KEY(s_num) REFERENCES subject(s_num)  -- S_NUM을 FK로 설정
);


INSERT INTO student(sd_num, sd_name, sd_id, sd_passwd, s_num, sd_birth, sd_phone, sd_address, sd_email)
VALUES('06010001', '김정수', 'javajsp', 'java1234', '01', TO_DATE('19860424', 'YYYYMMDD'), '01032789054', '(03727) 서울특별시 서대문구 성산로 450-2', 'javajsp@naver.com');

INSERT INTO student(sd_num, sd_name, sd_id, sd_passwd, s_num, sd_birth, sd_phone, sd_address, sd_email)
VALUES('95010002', '김수현', 'jdbcmania', 'mania12', '01', TO_DATE('19751009', 'YYYMMDD'), '01034524680', '(06774) 서울특별시 서초구 강남대로 27', 'jdbcmaniap@naver.com');

INSERT INTO student(sd_num, sd_name, sd_id, sd_passwd, s_num, sd_birth, sd_phone, sd_address, sd_email)
VALUES('98040001', '공지영', 'gonji', 'mani12', '04', TO_DATE('19780516','YYYYMMDD'), '01012657455', '(48000) 부산광역시 해운대구 반송로 816', 'gonji@nate.com');

INSERT INTO student(sd_num, sd_name, sd_id, sd_passwd, s_num, sd_birth, sd_phone, sd_address, sd_email)
VALUES('02050001', '조수영', 'water', 'java1234', '05', TO_DATE('19820831', 'YYYYMMDD'), '01076812499', '(34626) 대전광역시 동구 중앙로 215', 'water@korea.com');

INSERT INTO student(sd_num, sd_name, sd_id, sd_passwd, s_num, sd_birth, sd_phone, sd_address, sd_email)
VALUES('94040002', '최경란', 'novel', 'novel2468', '04', TO_DATE('19741025', 'YYYYMMDD'), '01098792649', '(16210) 경기도 수원시 장안구 서부로 2287-55', 'novel@naver.com');

INSERT INTO student(sd_num, sd_name, sd_id, sd_passwd, s_num, sd_birth, sd_phone, sd_address, sd_email)
VALUES('08020001', '안익태', 'korea', 'korea99', '02', TO_DATE('19880805', 'YYYYMMDD'), '01084522895', '(06181) 서울 강남구 테헤란로98길 12', 'korea@nate.com');


SELECT * FROM student;




-- 3. 과목테이블을 생성한다.
DROP TABLE course purge;

CREATE TABLE course (
    no          NUMBER          NOT NULL,   -- 일련번호
    c_num       CHAR(7)         NOT NULL,   -- 과목번호
    c_name      NVARCHAR2(80)   NOT NULL,   -- 과목명
    c_credit    NUMBER(2)       NOT NULL,   -- 학점
    c_section   NCHAR(2)        NOT NULL,   -- 과목구분
    CONSTRAINT COURSE_NO_PK PRIMARY KEY(no),    -- NO를 PK로 설정
    CONSTRAINT COURSE_C_NUM_UK UNIQUE(c_num),    -- C_NUM을 UK로 설정
    CONSTRAINT COURSE_C_CREDIT_CK CHECK(c_credit BETWEEN 2 AND 4),
    CONSTRAINT COURSE_C_SECTION_CK CHECK(c_section IN ('전공', '교양', '일반'))
);

-- 과목테이블에 일련번호(no)를 시퀀스에 의해 저장되도록 시퀀스 생성
CREATE SEQUENCE course_seq
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 999999
NOCYCLE
CACHE 2;

INSERT INTO course(no, c_num, c_name, c_credit, c_section)
VALUES(course_seq.NEXTVAL, 'UA04001', '대학영어', 2, '교양');

INSERT INTO course(no, c_num, c_name, c_credit, c_section)
VALUES(course_seq.NEXTVAL, 'UA05001', '소프트웨어와 창의적 사고', 4, '교양');

INSERT INTO course(no, c_num, c_name, c_credit, c_section)
VALUES(course_seq.NEXTVAL, 'UBB0001', '독서와 토론', 3, '교양');

INSERT INTO course(no, c_num, c_name, c_credit, c_section)
VALUES(course_seq.NEXTVAL, 'UGG0010', '한국의 이해' , 3, '일반');

INSERT INTO course(no, c_num, c_name, c_credit, c_section)
VALUES(course_seq.NEXTVAL, 'UGG0031', '내아이디어로 창업하기', 4, '일반');

INSERT INTO course(no, c_num, c_name, c_credit, c_section)
VALUES(course_seq.NEXTVAL, 'UCR0001', '데이터베이스 설계와 구축', 4, '전공');

INSERT INTO course(no, c_num, c_name, c_credit, c_section)
VALUES(course_seq.NEXTVAL, 'UCR0002', '데이터 분석', 4, '전공');

COMMIT;

SELECT * FROM course;


-- 4. 수강 테이블
DROP TABLE enrollment purge;

CREATE TABLE enrollment (
    no          NUMBER          NOT NULL, -- 일련번호
    e_year      CHAR(4)         NOT NULL, -- 수강년도
    e_semester  NVARCHAR2(4)    NOT NULL, -- 수강학기
    sd_num      CHAR(8)    NOT NULL, -- 학번
    c_num       CHAR(7)     NOT NULL, -- 과목번호
    e_grade     NUMBER(2,1)     NOT NULL, -- 성적
    e_date      DATE DEFAULT SYSDATE NOT NULL, -- 등록일자
    CONSTRAINT ENROLLMENT_NO_PK PRIMARY KEY(no),    -- NO를 PK로 설정
    CONSTRAINT ENROLLMENT_E_SEMESTER_CK CHECK(e_semester IN ('1학기', '2학기', '여름학기', '겨울학기')),
    CONSTRAINT ENROLLMENT_SD_NUM_FK FOREIGN KEY(sd_num) REFERENCES student(sd_num),  -- SD_NUM을 FK로 설정
    CONSTRAINT ENROLLMENT_C_NUM_FK FOREIGN KEY(c_num) REFERENCES course(c_num),  -- C_NUM을 FK로 설정
    CONSTRAINT ENROLLMENT_E_GRADE_CK CHECK(e_grade BETWEEN 0 AND 4.5)
);

CREATE SEQUENCE enrollment_seq
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 999999
NOCYCLE
CACHE 2;

INSERT INTO enrollment(no, e_year, e_semester, sd_num, c_num, e_grade)
VALUES(enrollment_seq.NEXTVAL, '2004', '1학기', '06010001', 'UA05001', 4.0);

INSERT INTO enrollment(no, e_year, e_semester, sd_num, c_num, e_grade)
VALUES(enrollment_seq.NEXTVAL, '2004', '1학기', '98040001', 'UBB0001', 3.8);

INSERT INTO enrollment(no, e_year, e_semester, sd_num, c_num, e_grade)
VALUES(enrollment_seq.NEXTVAL, '2004', '1학기', '06010001', 'UCR0001', 4.3);

INSERT INTO enrollment(no, e_year, e_semester, sd_num, c_num, e_grade)
VALUES(enrollment_seq.NEXTVAL, '2004', '1학기', '08020001' , 'UGG0031', 3.6);


COMMIT;

SELECT no, e_year, e_semester, sd_num, c_num, 
        TO_CHAR(e_grade, 'FM9.0') e_grade
FROM enrollment;

